'use client';

import { useState, useEffect } from 'react';
import type { ITab, IDraft } from '@/types/main.db';

// Advanced AI Service with Language Model Integration
export const useAIService = () => {
  const [aiSession, setAiSession] = useState<any>(null);
  const [aiStatus, setAiStatus] = useState<'loading' | 'ready' | 'error' | 'unavailable'>('loading');
  const [useServerAI, setUseServerAI] = useState(false);

  useEffect(() => {
    const initializeAI = async () => {
      try {
        if (!(window as any).LanguageModel) {
          console.log("LanguageModel API not found, falling back to server-side AI.");
          setUseServerAI(true);
          setAiStatus('ready');
          return;
        }

        const opts = {
          expectedOutputs: [{ type: "text", languages: ["en"] }]
        };

        const availability = await (window as any).LanguageModel.availability(opts);
        console.log("availability:", availability);

        if (availability === "unavailable") {
          console.error("❌ Model masih unavailable.");
          setAiStatus('unavailable');
          return;
        }

        const session = await (window as any).LanguageModel.create({
          ...opts,
          monitor(m: any) {
            m.addEventListener("downloadprogress", (e: any) => {
              console.log(`📥 Download progress: ${(e.loaded * 100).toFixed(1)}%`);
            });
            m.addEventListener("statechange", (e: any) => {
              console.log("⚡ State change:", e.target.state);
            });
          }
        });

        console.log("✅ Session ready:", session);
        setAiSession(session);
        setAiStatus('ready');

      } catch (err) {
        console.error("Error:", err);
        setAiStatus('error');
      }
    };

    initializeAI();
  }, []);

  const promptAI = async (prompt: string, type: string = 'summarize') => {
    if (useServerAI) {
      try {
        const response = await fetch('/api/ai/prompt', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({ prompt, type }),
        });
        if (!response.ok) {
          throw new Error('Server AI response was not ok.');
        }
        const data = await response.json();
        return data.response;
      } catch (error) {
        console.error("Error prompting server-side AI:", error);
        return "Error from server-side AI";
      }
    } else {
      if (!aiSession) {
        console.error("AI session not ready");
        return "AI not available";
      }
      try {
        const result = await aiSession.prompt(prompt);
        return result;
      } catch (error) {
        console.error("Error prompting AI:", error);
        return "Error from AI";
      }
    }
  };

  const generateSummary = async (content: string, type: 'tab' | 'draft') => {
    const prompt = `Summarize this ${type} content: ${content.substring(0, 2000)}`;
    return await promptAI(prompt, 'summarize');
  };

  const translateContent = async (content: string, targetLanguage: string) => {
    const prompt = `Translate to ${targetLanguage}: ${content.substring(0, 2000)}`;
    return await promptAI(prompt, 'translate');
  };

  const rewriteContent = async (content: string, style: string = 'academic') => {
    const prompt = `Rewrite in ${style} style: ${content.substring(0, 2000)}`;
    return await promptAI(prompt, 'rewrite');
  };

  const expandContent = async (content: string, context: string) => {
    const prompt = `Expand this content with ${context}: ${content.substring(0, 2000)}`;
    return await promptAI(prompt, 'expand');
  };

  const autoGenerateDraft = async (tabs: ITab[], theme: string) => {
    const tabContents = tabs.map(tab => 
      `Source: ${tab.title}\nContent: ${tab.content?.substring(0, 500)}`
    ).join('\n\n');
    
    const prompt = `Create a research draft about ${theme} using these sources:\n\n${tabContents}`;
    return await promptAI(prompt, 'draft');
  };

  const chatWithAI = async (message: string, context: { tabs: ITab[], drafts: IDraft[] }) => {
    const contextSummary = `Research Context: ${context.tabs.length} tabs, ${context.drafts.length} drafts`;
    const prompt = `${contextSummary}\n\nUser Question: ${message}`;
    return await promptAI(prompt, 'chat');
  };

  return {
    aiStatus,
    generateSummary,
    translateContent,
    rewriteContent,
    expandContent,
    autoGenerateDraft,
    chatWithAI,
    promptAI,
  };
};
